"""Project constants."""

DEFAULT_WEIGHTS = {
    "skill": 0.30,
    "semantic": 0.25,
    "experience": 0.15,
    "education": 0.10,
    "quality": 0.20,
}

EDUCATION_RANK = {
    "high school": 1,
    "diploma": 2,
    "associate": 3,
    "bachelor": 4,
    "master": 5,
    "phd": 6,
}

EDUCATION_KEYWORDS = {
    "phd": ["phd", "doctorate"],
    "master": ["master", "m.tech", "m.e", "m.s", "msc", "mba"],
    "bachelor": ["bachelor", "b.tech", "b.e", "b.s", "bsc", "bca"],
    "associate": ["associate"],
    "diploma": ["diploma"],
    "high school": ["high school", "12th", "10th"],
}

ACTION_VERBS = [
    "built",
    "designed",
    "developed",
    "implemented",
    "optimized",
    "improved",
    "led",
    "managed",
    "delivered",
    "automated",
    "deployed",
    "integrated",
    "created",
    "achieved",
    "reduced",
    "increased",
]

SKILL_CATALOG = [
    "Python",
    "Java",
    "C++",
    "JavaScript",
    "TypeScript",
    "SQL",
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "Pandas",
    "NumPy",
    "Scikit-learn",
    "TensorFlow",
    "PyTorch",
    "Machine Learning",
    "Deep Learning",
    "NLP",
    "Data Analysis",
    "Data Visualization",
    "FastAPI",
    "Flask",
    "Django",
    "REST API",
    "GraphQL",
    "Docker",
    "Kubernetes",
    "AWS",
    "Azure",
    "GCP",
    "Linux",
    "Git",
    "CI/CD",
    "Jenkins",
    "Airflow",
    "Spark",
    "Hadoop",
    "Power BI",
    "Tableau",
    "Excel",
    "HTML",
    "CSS",
    "React",
    "Node.js",
    "Streamlit",
    "LLM",
    "Prompt Engineering",
]

SKILL_ALIASES = {
    "REST API": ["restful api", "rest api", "api development"],
    "Node.js": ["nodejs", "node js"],
    "Scikit-learn": ["sklearn"],
    "Machine Learning": ["ml"],
    "Deep Learning": ["dl"],
    "Prompt Engineering": ["prompting"],
    "JavaScript": ["js"],
    "TypeScript": ["ts"],
    "PostgreSQL": ["postgres", "postgresql"],
}

